-- This file allow to write SQL commands that will be emitted in test and dev.
insert into usuario (id, nome, dataNascimento, pais) values (1,'Carlos', '1990-02-24', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (2,'Ana', '1985-07-15', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (3,'John', '1978-11-30', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (4,'Maria', '1992-05-20', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (5,'Li', '1988-09-10', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (6,'Fatima', '1995-12-01', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (7,'Ahmed', '1983-03-14', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (8,'Sophia', '1991-08-25', 'Brasil');
insert into usuario (id, nome, dataNascimento, pais) values (9,'Lucas', '1987-04-18', 'EUA');
insert into usuario (id, nome, dataNascimento, pais) values (10,'Emma', '1993-10-05', 'EUA');
insert into usuario (id, nome, dataNascimento, pais) values (11,'Oliver', '1989-06-22', 'EUA');
insert into usuario (id, nome, dataNascimento, pais) values (12,'Isabella', '1994-01-30', 'EUA');
insert into usuario (id, nome, dataNascimento, pais) values (13,'Mia', '1996-11-11', 'EUA');
insert into usuario (id, nome, dataNascimento, pais) values (14,'Ethan', '1984-07-07', 'EUA');
insert into usuario (id, nome, dataNascimento, pais) values (15,'Ava', '1992-03-19', 'China');
insert into usuario (id, nome, dataNascimento, pais) values (16,'James', '1986-12-29', 'China');
insert into usuario (id, nome, dataNascimento, pais) values (17,'Charlotte', '1990-09-09', 'China');
insert into usuario (id, nome, dataNascimento, pais) values (18,'Benjamin', '1988-05-03', 'China');
insert into usuario (id, nome, dataNascimento, pais) values (19,'Amelia', '1995-02-14', 'China');
insert into usuario (id, nome, dataNascimento, pais) values (20,'Henry', '1983-10-28', 'China');

INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (1, 'O Poderoso Chefão', 'Francis Ford Coppola', 1972, 'Crime');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (2, 'Pulp Fiction: Tempo de Violência', 'Quentin Tarantino', 1994, 'Crime');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (3, 'Forrest Gump: O Contador de Histórias', 'Robert Zemeckis', 1994, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (4, 'Matrix', 'Lana Wachowski, Lilly Wachowski', 1999, 'Ficção Científica');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (5, 'Gladiador', 'Ridley Scott', 2000, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (6, 'Clube da Luta', 'David Fincher', 1999, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (7, 'O Senhor dos Anéis: A Sociedade do Anel', 'Peter Jackson', 2001, 'Fantasia');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (8, 'O Cavaleiro das Trevas', 'Christopher Nolan', 2008, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (9, 'A Origem', 'Christopher Nolan', 2010, 'Ficção Científica');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (10, 'Interestelar', 'Christopher Nolan', 2014, 'Ficção Científica');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (11, 'Titanic', 'James Cameron', 1997, 'Romance');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (12, 'Avatar', 'James Cameron', 2009, 'Ficção Científica');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (13, 'Cisne Negro', 'Darren Aronofsky', 2010, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (14, 'O Resgate do Soldado Ryan', 'Steven Spielberg', 1998, 'Guerra');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (15, 'Jurassic Park', 'Steven Spielberg', 1993, 'Aventura');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (16, 'O Silêncio dos Inocentes', 'Jonathan Demme', 1991, 'Suspense');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (17, 'A Lista de Schindler', 'Steven Spielberg', 1993, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (18, 'De Volta para o Futuro', 'Robert Zemeckis', 1985, 'Aventura');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (19, 'Os Bons Companheiros', 'Martin Scorsese', 1990, 'Crime');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (20, 'Taxi Driver', 'Martin Scorsese', 1976, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (21, 'O Irlandês', 'Martin Scorsese', 2019, 'Crime');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (22, 'O Lobo de Wall Street', 'Martin Scorsese', 2013, 'Comédia');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (23, 'Django Livre', 'Quentin Tarantino', 2012, 'Faroeste');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (24, 'Bastardos Inglórios', 'Quentin Tarantino', 2009, 'Guerra');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (25, 'Kill Bill: Volume 1', 'Quentin Tarantino', 2003, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (26, 'Pantera Negra', 'Ryan Coogler', 2018, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (27, 'Vingadores: Ultimato', 'Anthony Russo, Joe Russo', 2019, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (28, 'Homem de Ferro', 'Jon Favreau', 2008, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (29, 'Capitão América: O Soldado Invernal', 'Anthony Russo, Joe Russo', 2014, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (30, 'Doutor Estranho', 'Scott Derrickson', 2016, 'Fantasia');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (31, 'Guardiões da Galáxia', 'James Gunn', 2014, 'Ficção Científica');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (32, 'Homem-Aranha: Sem Volta Para Casa', 'Jon Watts', 2021, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (33, 'Coringa', 'Todd Phillips', 2019, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (34, 'Batman Begins', 'Christopher Nolan', 2005, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (35, 'A Origem dos Guardiões', 'Peter Ramsey', 2012, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (36, 'Divertida Mente', 'Pete Docter', 2015, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (37, 'Procurando Nemo', 'Andrew Stanton', 2003, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (38, 'Toy Story', 'John Lasseter', 1995, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (39, 'Up: Altas Aventuras', 'Pete Docter', 2009, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (40, 'Soul', 'Pete Docter', 2020, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (41, 'Wall-E', 'Andrew Stanton', 2008, 'Ficção Científica');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (42, 'O Rei Leão', 'Roger Allers, Rob Minkoff', 1994, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (43, 'Shrek', 'Andrew Adamson, Vicky Jenson', 2001, 'Animação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (44, 'Os Incríveis', 'Brad Bird', 2004, 'Ação');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (45, 'Ratatouille', 'Brad Bird', 2007, 'Comédia');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (46, 'O Grande Gatsby', 'Baz Luhrmann', 2013, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (47, 'La La Land: Cantando Estações', 'Damien Chazelle', 2016, 'Musical');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (48, 'Whiplash: Em Busca da Perfeição', 'Damien Chazelle', 2014, 'Drama');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (49, 'Parasita', 'Bong Joon-ho', 2019, 'Suspense');
INSERT INTO movie (id, titulo, diretor, anoLancamento, genero) VALUES (50, 'Tudo em Todo Lugar ao Mesmo Tempo', 'Daniel Kwan, Daniel Scheinert', 2022, 'Ficção Científica');
